# PanOS-Software install process
---
- name: PanOS-Software install process
  gather_facts: true
  connection: local
  hosts: PaloAltoFirewalls

  tasks:
  
  name: hybrid port  
  - panos_restart:
      ip_address: "{{ hosts }}"
      password: "{{ password }}"
